-- GENERATED by apps/member/scripts/gen-seed.mjs from apps/member/src/data/fixtures.ts. Do not edit by hand.
-- The catalog: partners, trainers, classes, training paths and the weekly timetable. Loaded into the
-- hosted project, then `select public.extend_schedule()` (also run daily by pg_cron) makes sessions.

insert into public.partners (id, name, short_name, type, street, address, lat, lng, rating, parking, meet_at) values
  ('ridgeline', 'Ridgeline Dog Sport', 'Ridgeline', 'sport_club', 'Manor Rd', '4410 Manor Rd', 30.2905, -97.6985, 4.9, 'Park in the gravel lot by the gate', 'Barn gate, field 2'),
  ('northside', 'Northside Canine', 'Northside', 'facility', 'Burnet Rd', '5701 Burnet Rd', 30.329, -97.739, 4.8, 'Street parking on Burnet', 'Front desk'),
  ('eastfield', 'Eastfield Park', 'Eastfield', 'outdoor_space', 'Webberville Rd', '2200 Webberville Rd', 30.269, -97.702, 4.7, 'Lot at the north field', 'North field gate'),
  ('eastside', 'Eastside Dog Club', 'Eastside', 'facility', 'E Cesar Chavez St', '1914 E Cesar Chavez St', 30.258, -97.723, 4.9, 'Back lot, use the side gate', 'Side gate by the yard'),
  ('southfork', 'South Fork Yard', 'South Fork', 'outdoor_space', 'S Lamar Blvd', '3600 S Lamar Blvd', 30.24, -97.786, 4.6, 'Two spots by the yard gate', 'Yard gate');

insert into public.trainers (id, partner_id, name, credential, photo_url, rating) values
  ('maren', 'ridgeline', 'Maren Holt', 'AKC herding judge · 14 years', 'lab', 4.9),
  ('dev', 'ridgeline', 'Dev Patel', 'Agility and sprint coach · 9 years', 'sprint', 4.8),
  ('ana', 'northside', 'Ana Ruiz', 'Reactivity and recall · CPDT-KA', 'grass', 4.9),
  ('sam', 'eastside', 'Sam Reyes', 'Reactivity specialist · 11 years', 'rail', 5),
  ('lena', 'eastfield', 'Lena Brooks', 'Open field host · Pet first aid', 'leap', 4.7);

insert into public.class_types (id, partner_id, trainer_id, title, discipline, category, session_type, credits, duration_min,
  intensity, group_size, suits, suits_note, balance, description, image, premium, requires, grants, open_window, requirements) values
  ('herding-fundamentals', 'ridgeline', 'maren', 'Herding Fundamentals', 'Herding', 'sport', 'class', 2, 60, 4, 6, 'High energy', 'Loves dogs, selective', 'mental', 'Juno works a small flock of ducks on a fenced field with a trainer beside her. The session covers stock awareness, outruns and a calm stop. You stay on the field and learn the handling cues. Expect a tired, focused dog.', 'collie', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"},{"icon":"cake","text":"12 months or older"},{"icon":"link","text":"On leash until the trainer releases Juno"}]'::jsonb),
  ('herding-livestock', 'ridgeline', 'maren', 'Herding on Livestock', 'Herding', 'sport', 'class', 4, 75, 5, 4, 'Working dog', 'Herding breeds', 'mental', 'Sheep, not ducks. Juno works a full flock in the big pasture with Maren on the field. Bigger outruns, longer drives and a pen at the end. For dogs past Herding Fundamentals.', 'collie', true, 'herding', null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"},{"icon":"cake","text":"12 months or older"},{"icon":"link","text":"On leash until the trainer releases Juno"}]'::jsonb),
  ('herding-assessment', 'ridgeline', 'maren', 'Herding assessment', 'Herding', 'sport', 'assessment', 2, 30, 3, 1, 'Any energy', 'One dog at a time', 'mental', 'Maren watches Juno on a small flock and checks stock instinct, recall off stock and a calm stop. Passing opens livestock classes at Ridgeline. The result stays at this partner.', 'collie', false, null, 'herding', null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"},{"icon":"cake","text":"12 months or older"},{"icon":"link","text":"On leash until the trainer releases Juno"}]'::jsonb),
  ('agility-drop-in', 'ridgeline', 'dev', 'Agility drop-in', 'Agility', 'sport', 'class', 2, 50, 4, 8, 'High energy', 'Loves dogs', 'physical', 'Tunnels, jumps and weave poles on the indoor turf. Dev sets a short course for each level and runs dogs one at a time. Bring treats Juno will work for.', 'weave', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"},{"icon":"cake","text":"12 months or older"},{"icon":"link","text":"On leash until the trainer releases Juno"}]'::jsonb),
  ('lure-sprint', 'eastfield', 'dev', 'Lure Sprint Heats', 'Sprint', 'sport', 'class', 2, 40, 5, 8, 'High energy', 'Sound in body', 'physical', 'Timed straight-line heats behind a lure on the long field. Three to four runs with rest between. Every heat is timed, so you can watch Juno get faster.', 'sprint', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"},{"icon":"cake","text":"12 months or older"}]'::jsonb),
  ('fitness', 'northside', 'ana', 'Fitness and conditioning', 'Fitness', 'sport', 'class', 2, 45, 3, 6, 'Any energy', 'Good with dogs nearby', 'physical', 'Balance work, cavaletti poles and core exercises that keep a sport dog sound. Low impact and a good partner to sprint and agility days.', 'hurdle', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"},{"icon":"link","text":"On leash until the trainer releases Juno"}]'::jsonb),
  ('scent-work', 'northside', 'ana', 'Scent Work I', 'Scent', 'scent', 'class', 2, 45, 2, 6, 'Any energy', 'Works alone, crated between turns', 'mental', 'Juno learns to find a target odor in boxes, then in a room. Dogs search one at a time, so it suits dogs who need space. Expect a calm, tired dog.', 'grass', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"}]'::jsonb),
  ('sniff-space', 'southfork', 'lena', 'Sniff space', 'Sniff', 'scent', 'class', 1, 45, 1, 1, 'Any energy', 'Private yard, your dogs only', 'mental', 'A fenced private yard for your dogs only. Let Juno sniff, roam and decompress. Book a 45-minute slot inside the open window.', 'wall', false, null, null, 'Open 4:00 to 8:00 pm', '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"}]'::jsonb),
  ('open-field', 'eastfield', 'lena', 'Open Field Session', 'Open play', 'play', 'class', 1, 90, 3, 20, 'Any energy', 'Loves dogs', 'physical', 'Five fenced acres with a host on the field. Run, swim in the stock tank and play with other dogs. Leave when Juno is done.', 'leap', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"},{"icon":"cake","text":"12 months or older"}]'::jsonb),
  ('free-roam', 'eastside', 'sam', 'Free roam', 'Open play', 'play', 'class', 1, 60, 3, 12, 'Any energy', 'Loves dogs', 'social', 'Off-leash play in the club yard with a handler watching the group. Dogs are matched by size and play style at the gate.', 'grass', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"},{"icon":"cake","text":"12 months or older"}]'::jsonb),
  ('small-group-play', 'eastside', 'sam', 'Small-group play', 'Play', 'play', 'class', 1, 45, 2, 5, 'Any energy', 'Selective dogs welcome', 'social', 'Five dogs, one trainer, a quiet yard. Sam picks calm play partners and steps in early. A good next step for dogs working on manners around other dogs.', 'tunnel', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"},{"icon":"cake","text":"12 months or older"}]'::jsonb),
  ('focus-recall', 'northside', 'ana', 'Focus and Recall', 'Skills', 'skills', 'class', 2, 45, 2, 6, 'Any energy', 'Good with dogs nearby', 'mental', 'Eye contact, a reliable come and a solid wait, practiced with more distractions each round. You handle, Ana coaches.', 'hurdle', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"},{"icon":"link","text":"On leash until the trainer releases Juno"}]'::jsonb),
  ('loose-leash', 'northside', 'ana', 'Loose leash 1:1', 'Skills', 'skills', 'private', 3, 45, 2, 1, 'Any energy', 'Private session', 'mental', 'A private session on the streets around Northside. Ana works on pace, turns and what to do when Juno pulls. You leave with three things to practice.', 'rail', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"}]'::jsonb),
  ('calm-private', 'eastside', 'sam', 'Calm around dogs', 'Skills', 'skills', 'private', 3, 40, 2, 1, 'Any energy', 'Private session', 'social', 'Sam works Juno at a distance from a calm helper dog and closes the gap as she settles. Each session ends before she gets stuck.', 'lab', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"}]'::jsonb),
  ('social-assessment', 'eastside', 'sam', 'Social assessment', 'Assessment', 'skills', 'assessment', 2, 30, 2, 1, 'Any energy', 'One dog at a time', 'social', 'Sam meets Juno one-on-one, then with a calm helper dog, and watches how she reads other dogs, settles and recovers from a startle. Passing earns the Social clearance, which opens group sport, play and group skills at every PackPass partner. Not yet means a short training path first.', 'rail', false, null, 'social', null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"}]'::jsonb),
  ('social-recheck', 'eastside', 'sam', 'Social re-check', 'Assessment', 'skills', 'assessment', 2, 30, 2, 1, 'Any energy', 'One dog at a time', 'social', 'Sam watches Juno in a calm small group and checks how she reads other dogs, recovers from a startle and settles. Passing earns the Social clearance, which opens group sport, play and group skills at every PackPass partner.', 'tunnel', false, null, 'social', null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"}]'::jsonb),
  ('parallel-walk', 'eastside', 'sam', 'Parallel walk', 'Skills', 'skills', 'private', 3, 45, 2, 1, 'Any energy', 'Private session', 'social', 'Juno and a steady helper dog walk the same route on opposite sides of the street, then closer. Step 2 of Calm around dogs.', 'wall', false, null, null, null, '[{"icon":"syringe","text":"Rabies, DHPP and Bordetella current"}]'::jsonb);

insert into public.training_paths (id, title, lede, grants) values
  ('calm-around-dogs', 'Calm around dogs', 'Finish this path to earn a Social clearance and access to group sport.', 'social'),
  ('loose-leash-walking', 'Loose leash walking', 'Finish this path to walk your dog past other dogs on a loose leash.', null);

insert into public.path_steps (path_id, position, title, class_id) values
  ('calm-around-dogs', 1, 'Distance work', 'calm-private'),
  ('calm-around-dogs', 2, 'Parallel walk', 'parallel-walk'),
  ('calm-around-dogs', 3, 'Small-group play', 'small-group-play'),
  ('calm-around-dogs', 4, 'Social re-check', 'social-recheck'),
  ('loose-leash-walking', 1, '1:1 intro', 'loose-leash'),
  ('loose-leash-walking', 2, 'Quiet streets', 'loose-leash'),
  ('loose-leash-walking', 3, 'Calm walk past dogs', 'focus-recall');

-- Weekly timetable (Austin time). weekday null = every day, 0 = Sunday.
insert into public.timetable (class_id, weekday, starts) values
  ('agility-drop-in', null, '18:30'),
  ('lure-sprint', null, '19:00'),
  ('herding-assessment', null, '18:45'),
  ('fitness', null, '19:15'),
  ('herding-livestock', null, '19:00'),
  ('scent-work', null, '18:00'),
  ('sniff-space', null, '16:00'),
  ('open-field', null, '17:00'),
  ('free-roam', null, '17:30'),
  ('small-group-play', null, '18:30'),
  ('focus-recall', null, '17:30'),
  ('loose-leash', null, '18:15'),
  ('calm-private', null, '19:00'),
  ('herding-fundamentals', 4, '07:30'),
  ('herding-fundamentals', 4, '09:00'),
  ('herding-fundamentals', 4, '17:30'),
  ('parallel-walk', 4, '16:00'),
  ('herding-livestock', 6, '08:00'),
  ('loose-leash', 6, '09:00'),
  ('social-recheck', 6, '10:00'),
  ('social-assessment', 3, '10:30'),
  ('social-assessment', 6, '11:00');
