-- GENERATED by apps/member/scripts/gen-seed.mjs from apps/member/src/data/fixtures.ts. Do not edit by hand.
-- Local development only (runs after catalog.sql): sample sessions and seed_demo_member().

-- Sessions for the next 28 days in Austin time, with the app's sample spot counts.
with daily(class_id, t, spots) as (values
  ('agility-drop-in', '18:30', 4),
  ('lure-sprint', '19:00', 0),
  ('herding-assessment', '18:45', 2),
  ('fitness', '19:15', 5),
  ('herding-livestock', '19:00', 1),
  ('scent-work', '18:00', 5),
  ('sniff-space', '16:00', 3),
  ('open-field', '17:00', 12),
  ('free-roam', '17:30', 8),
  ('small-group-play', '18:30', 4),
  ('focus-recall', '17:30', 3),
  ('loose-leash', '18:15', 1),
  ('calm-private', '19:00', 2)
), weekly(class_id, dow, t, spots) as (values
  ('herding-fundamentals', 4, '07:30', 4),
  ('herding-fundamentals', 4, '09:00', 3),
  ('herding-fundamentals', 4, '17:30', 6),
  ('parallel-walk', 4, '16:00', 1),
  ('herding-livestock', 6, '08:00', 1),
  ('loose-leash', 6, '09:00', 1),
  ('social-recheck', 6, '10:00', 2),
  ('social-assessment', 3, '10:30', 3),
  ('social-assessment', 6, '11:00', 3)
), days as (
  select (current_date + d) as day, d from generate_series(0, 27) d
), slots as (
  select class_id, day, d, t, spots from daily cross join days
  union all
  select class_id, day, d, t, spots from weekly join days on extract(dow from day) = weekly.dow
)
insert into public.sessions (class_id, starts_at, capacity, packpass_spots, spots_left)
select s.class_id,
       (s.day + s.t::time) at time zone 'America/Chicago',
       c.group_size,
       c.group_size,
       least(c.group_size, greatest(0, case when s.d = 0 then s.spots else s.spots + ((s.d * 7 + s.spots * 3) % 5) - 1 end))
from slots s join public.class_types c on c.id = s.class_id;

-- Gives an existing account Juno (and Otis) as the designs show them: vaccines on file, on step 2 of
-- Calm around dogs after a "not yet" Social assessment, Herding Fundamentals booked for Thursday.
-- Run from the SQL editor after signing up: select public.seed_demo_member('<user id>');
create or replace function public.seed_demo_member(p_user uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  juno uuid;
  otis uuid;
  hf uuid;
begin
  insert into public.dogs (owner_id, name, sex, breed, birth_month, birth_year, weight_lb, fixed, energy, sociability, interests, traits, area, member_since)
  values (p_user, 'Juno', 'female', 'Border Collie', 3, 2023, 38, true, 'working', 'loves_dogs', '{Herding,Sprint,Scent}',
          '{"Pulls on the leash","Nervous with new dogs"}', 'Austin · South', 2026)
  returning id into juno;
  insert into public.dogs (owner_id, name, sex, breed, birth_year, energy, sociability, member_since)
  values (p_user, 'Otis', 'male', 'Labrador', 2020, 'medium', 'loves_dogs', 2026) returning id into otis;

  insert into public.vaccinations (dog_id, type, expires_on, verified) values
    (juno, 'rabies', '2028-03-01', true), (juno, 'dhpp', '2027-01-01', true), (juno, 'bordetella', current_date + 15, true);

  insert into public.dog_paths (dog_id, path_id, next_step) values (juno, 'calm-around-dogs', 2), (juno, 'loose-leash-walking', 1);
  insert into public.assessments (dog_id, type, partner_id, assessor, outcome, assessed_on, strengths, working_on, quote) values
    (juno, 'social', 'eastside', 'Sam Reyes', 'not_yet', current_date - 17,
     '{"Calm one-on-one","Recovers fast after a startle","Easy to handle at the gate"}',
     '{"Fixates on new dogs at the gate","Fixates for the first few minutes"}',
     'Juno did well one-on-one and settled after ten minutes. She still fixates on new dogs at the gate. Two sessions should get her there.');

  select s.id into hf from public.sessions s
  where s.class_id = 'herding-fundamentals' and s.starts_at > now() and s.spots_left > 0 order by s.starts_at limit 1;
  insert into public.bookings (session_id, dog_id, member_id, credits_charged) values (hf, juno, p_user, 2);
  update public.sessions set spots_left = spots_left - 1 where id = hf;
  update public.profiles set credits_balance = 7 where id = p_user;
  insert into public.credit_ledger (member_id, delta, reason) values (p_user, -3, 'adjustment');
  return juno;
end $$;
revoke execute on function public.seed_demo_member from public, anon, authenticated;
