// Generates two files from the app's sample data (src/data/fixtures.ts), so the database and the
// app's offline mode show the same partners, classes and schedule:
//   supabase/catalog.sql  partners, trainers, classes, training paths and the weekly timetable.
//                         Safe for the hosted project (until the partner dashboard writes these).
//   supabase/seed.sql     local only: four weeks of sessions with sample spot counts, and
//                         seed_demo_member() to give a test account Juno's Passport.
// Usage: npm run gen:seed

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import ts from 'typescript';

const here = path.dirname(fileURLToPath(import.meta.url));
const app = path.resolve(here, '..');
const out = path.resolve(app, '../../supabase/seed.sql');
const catalogOut = path.resolve(app, '../../supabase/catalog.sql');

// Load fixtures.ts without Metro: transpile to CommonJS and stub image requires.
const src = fs.readFileSync(path.join(app, 'src/data/fixtures.ts'), 'utf8');
const js = ts.transpileModule(src, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
const mod = { exports: {} };
vm.runInNewContext(js, { module: mod, exports: mod.exports, require: (p) => (p.endsWith('.jpg') ? p : {}) });
const { partners, trainers, classes, DAILY, WEEKLY, SCHEDULE_DAYS } = mod.exports;

const q = (v) => (v === undefined || v === null ? 'null'
  : Array.isArray(v) ? `'{${v.map((x) => `"${x}"`).join(',')}}'`
  : typeof v === 'number' || typeof v === 'boolean' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const rows = (list) => list.map((r) => `  (${r.map(q).join(', ')})`).join(',\n');

const PARTNER_TYPE = { ridgeline: 'sport_club', northside: 'facility', eastfield: 'outdoor_space', eastside: 'facility', southfork: 'outdoor_space' };
// Approximate locations in Austin (for distances in live mode).
const COORDS = { ridgeline: [30.2905, -97.6985], northside: [30.329, -97.739], eastfield: [30.269, -97.702], eastside: [30.258, -97.723], southfork: [30.24, -97.786] };
const MEET_AT = { ridgeline: 'Barn gate, field 2', northside: 'Front desk', eastfield: 'North field gate', eastside: 'Side gate by the yard', southfork: 'Yard gate' };
const TRAINER_PARTNER = { maren: 'ridgeline', dev: 'ridgeline', ana: 'northside', sam: 'eastside', lena: 'eastfield' };
// Starting specialties (partners change them on the dashboard's Trainers page).
const TRAINER_SPECIALTIES = {
  maren: ['Herding', 'Recall'], dev: ['Fitness and conditioning', 'Recall'], ana: ['Reactivity', 'Recall', 'Leash skills'],
  sam: ['Reactivity', 'Separation'], lena: ['Puppy foundations'],
};

const PATHS = [
  ['calm-around-dogs', 'Calm around dogs', 'Finish this path to earn a Social clearance and access to group sport.', 'social',
    [['Distance work', 'calm-private'], ['Parallel walk', 'parallel-walk'], ['Small-group play', 'small-group-play'], ['Social re-check', 'social-recheck']],
    ['Reactivity', 'Separation', 'Behaviorist']],
  ['loose-leash-walking', 'Loose leash walking', 'Finish this path to walk your dog past other dogs on a loose leash.', null,
    [['1:1 intro', 'loose-leash'], ['Quiet streets', 'loose-leash'], ['Calm walk past dogs', 'focus-recall']],
    ['Leash skills', 'Recall', 'Puppy foundations']],
];

const catalog = `-- GENERATED by apps/member/scripts/gen-seed.mjs from apps/member/src/data/fixtures.ts. Do not edit by hand.
-- The catalog: partners, trainers, classes, training paths and the weekly timetable. Loaded into the
-- hosted project, then \`select public.extend_schedule()\` (also run daily by pg_cron) makes sessions.

insert into public.partners (id, name, short_name, type, street, address, lat, lng, rating, parking, meet_at) values
${rows(Object.values(partners).map((p) => [p.id, p.name, p.short, PARTNER_TYPE[p.id], p.street, p.address, COORDS[p.id][0], COORDS[p.id][1], p.rating, p.parking, MEET_AT[p.id]]))};

insert into public.trainers (id, partner_id, name, credential, photo_url, rating, specialties) values
${rows(Object.values(trainers).map((t) => [t.id, TRAINER_PARTNER[t.id], t.name, t.credential, t.photo, t.rating, TRAINER_SPECIALTIES[t.id] ?? []]))};

insert into public.class_types (id, partner_id, trainer_id, title, discipline, category, session_type, credits, duration_min,
  intensity, group_size, suits, suits_note, balance, description, image, premium, requires, grants, open_window, requirements) values
${Object.values(classes).map((c) => `  (${[c.id, c.partnerId, c.trainerId, c.title, c.discipline, c.category.toLowerCase(), c.sessionType.toLowerCase(),
  c.credits, c.durationMin, c.intensity, c.groupSize, c.suits, c.suitsNote, c.balance.toLowerCase(), c.description, c.image, !!c.premium,
  c.requires, c.grants, c.openWindow].map(q).join(', ')}, ${q(JSON.stringify(c.requirements))}::jsonb)`).join(',\n')};

insert into public.training_paths (id, title, lede, grants, specialties) values
${rows(PATHS.map(([id, title, lede, grants, , specs]) => [id, title, lede, grants, specs]))};

insert into public.path_steps (path_id, position, title, class_id) values
${rows(PATHS.flatMap(([id, , , , steps]) => steps.map(([title, cls], i) => [id, i + 1, title, cls])))};

-- Weekly timetable (Austin time). weekday null = every day, 0 = Sunday.
insert into public.timetable (class_id, weekday, starts) values
${rows([...DAILY.map(([c, t]) => [c, null, t]), ...WEEKLY.map(([c, d, t]) => [c, d, t])])};
`;

const sql = `-- GENERATED by apps/member/scripts/gen-seed.mjs from apps/member/src/data/fixtures.ts. Do not edit by hand.
-- Local development only (runs after catalog.sql): sample sessions and seed_demo_member().

-- Sessions for the next ${SCHEDULE_DAYS} days in Austin time, with the app's sample spot counts.
with daily(class_id, t, spots) as (values
${rows(DAILY)}
), weekly(class_id, dow, t, spots) as (values
${rows(WEEKLY)}
), days as (
  select (current_date + d) as day, d from generate_series(0, ${SCHEDULE_DAYS - 1}) d
), slots as (
  select class_id, day, d, t, spots from daily cross join days
  union all
  select class_id, day, d, t, spots from weekly join days on extract(dow from day) = weekly.dow
)
insert into public.sessions (class_id, starts_at, capacity, packpass_spots, spots_left)
select s.class_id,
       (s.day + s.t::time) at time zone 'America/Chicago',
       c.group_size,
       c.group_size,
       least(c.group_size, greatest(0, case when s.d = 0 then s.spots else s.spots + ((s.d * 7 + s.spots * 3) % 5) - 1 end))
from slots s join public.class_types c on c.id = s.class_id;

-- Gives an existing account Juno (and Otis) as the designs show them: vaccines on file, on step 2 of
-- Calm around dogs after a "not yet" Social assessment, Herding Fundamentals booked for Thursday.
-- Run from the SQL editor after signing up: select public.seed_demo_member('<user id>');
create or replace function public.seed_demo_member(p_user uuid) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  juno uuid;
  otis uuid;
  hf uuid;
begin
  insert into public.dogs (owner_id, name, sex, breed, birth_month, birth_year, weight_lb, fixed, energy, sociability, interests, traits, area, member_since)
  values (p_user, 'Juno', 'female', 'Border Collie', 3, 2023, 38, true, 'working', 'loves_dogs', '{Herding,Sprint,Scent}',
          '{"pulls","nervous_dogs"}', 'Austin · South', 2026)
  returning id into juno;
  insert into public.dogs (owner_id, name, sex, breed, birth_year, energy, sociability, member_since)
  values (p_user, 'Otis', 'male', 'Labrador', 2020, 'medium', 'loves_dogs', 2026) returning id into otis;

  insert into public.vaccinations (dog_id, type, expires_on, verified) values
    (juno, 'rabies', '2028-03-01', true), (juno, 'dhpp', '2027-01-01', true), (juno, 'bordetella', current_date + 15, true);

  insert into public.dog_paths (dog_id, path_id, next_step) values (juno, 'calm-around-dogs', 2), (juno, 'loose-leash-walking', 1);
  insert into public.assessments (dog_id, type, partner_id, assessor, outcome, assessed_on, strengths, working_on, quote) values
    (juno, 'social', 'eastside', 'Sam Reyes', 'not_yet', current_date - 17,
     '{"Calm one-on-one","Recovers fast after a startle","Easy to handle at the gate"}',
     '{"Fixates on new dogs at the gate","Fixates for the first few minutes"}',
     'Juno did well one-on-one and settled after ten minutes. She still fixates on new dogs at the gate. Two sessions should get her there.');

  select s.id into hf from public.sessions s
  where s.class_id = 'herding-fundamentals' and s.starts_at > now() and s.spots_left > 0 order by s.starts_at limit 1;
  insert into public.bookings (session_id, dog_id, member_id, credits_charged) values (hf, juno, p_user, 2);
  update public.sessions set spots_left = spots_left - 1 where id = hf;
  update public.profiles set credits_balance = 7 where id = p_user;
  insert into public.credit_ledger (member_id, delta, reason) values (p_user, -3, 'adjustment');
  return juno;
end $$;
revoke execute on function public.seed_demo_member from public, anon, authenticated;
`;

fs.writeFileSync(catalogOut, catalog);
fs.writeFileSync(out, sql);
console.log('wrote', path.relative(process.cwd(), out));
